# Generated by Django 4.1 on 2023-01-11 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatRoom', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
