# Generated by Django 4.1 on 2023-01-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatRoom', '0004_friendrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.BooleanField(default=True),
        ),
    ]
