# Generated by Django 4.1 on 2023-01-12 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatRoom', '0005_alter_message_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='users',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
