# Generated by Django 4.1 on 2023-01-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatRoom', '0005_user_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='theme',
        ),
        migrations.AddField(
            model_name='user',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
    ]
