# Generated by Django 4.1 on 2023-01-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatRoom', '0005_alter_user_friends_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, to='chatRoom.user'),
        ),
    ]
