# Generated by Django 4.1 on 2023-01-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatRoom', '0006_remove_user_theme_user_dark_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dark_mode',
        ),
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.IntegerField(choices=[(1, 'Light'), (2, 'Dark')], default=1),
        ),
    ]
