# Generated by Django 4.1 on 2023-01-09 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatRoom', '0007_rename_user_accounts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accounts',
            new_name='Account',
        ),
    ]
