# Generated by Django 4.1 on 2023-01-12 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatRoom', '0007_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='owner',
        ),
    ]
