# Generated by Django 4.1 on 2023-01-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatRoom', '0007_remove_user_dark_mode_user_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='theme',
            field=models.IntegerField(choices=[(0, 'Light'), (1, 'Dark')], default=1),
        ),
    ]
