# Generated by Django 4.1 on 2023-01-12 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatRoom', '0008_remove_room_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='users',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
