# Generated by Django 4.1 on 2023-01-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatRoom', '0009_alter_account_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
